# https://github.com/actions/labeler

name: PR Labels
on:
- pull_request

jobs:
  apply:
    if: github.repository == 'fanny-jiang/integrations-core'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Add labels
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/workflows/config/labeler.yml
